development:
  adapter: postgresql
  encoding: unicode
  database: recipe_guru_development
  pool: 20
  username: postgres
  password: 
  min_messages: WARNING
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: recipe_guru_test
  pool: 5
  username: postgres
  password: 
  min_messages: WARNING
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: recipe_guru_production 
  port: 5432
  pool: 20
